name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: frontend
        run: |
          echo "Installing dependencies in:"
          pwd
          npm install

      - name: Build
        working-directory: frontend
        run: |
          echo "Building in:"
          pwd
          npm run build
          echo "Build directory contents:"
          ls -la dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist 